language: python
python:
  - "3.8"
env:
  - TOXENV=py36-2.2
  - TOXENV=py36-3.0
  - TOXENV=py36-3.1
  - TOXENV=py37-2.2
  - TOXENV=py37-3.0
  - TOXENV=py37-3.1
  - TOXENV=py38-2.2
  - TOXENV=py38-3.0
  - TOXENV=py38-3.1
install:
  - pip install -q --use-mirrors tox==3.19.0
script:
  - tox
